# Generated by Django 2.2.1 on 2019-06-18 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlister.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='SongLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streaming_service_name', models.CharField(max_length=250)),
                ('streaming_service_url', models.CharField(max_length=2000)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlister.Song')),
            ],
        ),
    ]
