# Generated by Django 2.2.1 on 2019-06-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='playlist',
        ),
    ]
