# Generated by Django 2.2.1 on 2019-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0002_auto_20190622_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
