# Generated by Django 2.2.1 on 2019-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlister', '0003_auto_20190625_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='desc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playlist',
            name='mood',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
